name: Build ocmod zip on Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build paydo.ocmod.zip
        run: |
          git archive --format=zip --output=paydo.ocmod.zip HEAD

      - name: Upload asset to Release
        uses: softprops/action-gh-release@v2
        with:
          files: paydo.ocmod.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
